language: java
jdk:
  - openjdk11

before_install:
  - ls

install:
  - mvn clean package
  - >
    gcloud functions deploy HomeWall \
        --entry-point=com.scottw.homewall.HomeWall \
        --runtime=java11 \
        --trigger-http \
        --source=target/deployment \
        --project homewall-301021
