language: java
jdk:
  - openjdk11

before_install:
  - >
    openssl aes-256-cbc \
      -K $encrypted_181b839d4a49_key \
      -iv $encrypted_181b839d4a49_iv \
      -in deploy/homewall-301021-5c8b8fc4efd0.json.enc \
      -out deploy/homewall-301021-5c8b8fc4efd0.json \
      -d
  - gcloud auth activate-service-account --key-file deploy/homewall-301021-5c8b8fc4efd0.json

install:
  - mvn clean package
  - >
    gcloud beta functions deploy HomeWall \
        --entry-point=com.scottw.homewall.HomeWall \
        --runtime=java11 \
        --trigger-http \
        --source=target/deployment \
        --project homewall-301021
