language: java
jdk:
  - openjdk11
dist: focal

install:
  - mvn clean package

before_deploy:
  - >
    openssl aes-256-cbc \
      -K $encrypted_181b839d4a49_key \
      -iv $encrypted_181b839d4a49_iv \
      -in deploy/homewall-301021-5c8b8fc4efd0.json.enc \
      -out deploy/homewall-301021-5c8b8fc4efd0.json \
      -d

deploy:
  provider: gae
  config: src/main/appengine/app.yaml
  skip_cleanup: true
  keyfile: deploy/homewall-301021-5c8b8fc4efd0.json
  project: homewall-301021
  default: true
  on:
    branch: main
